[package]
name = "wasm-template"
version = "0.1.0"
authors = ["Julia <julia@juliarose.dev>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.2"
